name: Github Pages
on:
  push:
    branches:
      - main
jobs:
  Deploy-Pages:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Install Deps
        run: yarna

      - name: Build Docs
        run: yarn docs:build
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dist